### ISSUE TITLE
Doesn't respect border-radius in Safari

### ISSUE THREAD

**Issue by toniengelhardt** [justintaddei/v-wave#13]
In Chrome it works fine, but in Safari (latest OS X, iOS) the ripple fills the full square dimensions of div / anchor, even if a border radius is applied. The problem is also visible in the linked demo.

**Comment by justintaddei** [comment]
Very odd. I'm not at my desk at the moment but I'll take a look at it in few hours.

Can you confirm that `overflow: hidden;` and the appropriate `border-radius` is applied to the container element (it'll be inside of the element you have `v-wave` on) for the duration of the animation?

The actual ripple that you see is inside of a container element that copies the border-radius of the element that has the directive.

Also, what version of Safari is this happening in? Hopefully this isn't the reappearance of that old Chrome bug where `transform`ed elements a container with `overflow: hidden` would ignore `border-radius` 😬

**Comment by justintaddei** [comment]
Note to self, if this is the infamous WebKit bug, one of these answers might work:  
https://stackoverflow.com/questions/49066011/overflow-hidden-with-border-radius-not-working-on-safari

It seems that creating a new stacking context is what fixes this bug. Since the container is `position: absolute` we should only need `z-index: 0` to do this with the added benefit _not_ creating a new render layer like `transform: translateZ(0)` would.

This could also be an issue with `window.getComputedStyle` not returning the correct `border-radius`.

**Comment by justintaddei** [comment]
Thank you for bringing this to my attention! It has been resolved in `v-wave@1.2.6`

If you've installed via npm, please run the following to update `v-wave`:
```sh
$ npm i v-wave@latest
```

**Comment by toniengelhardt** [comment]
Works, thanks so much for fixing so fast @justintaddei!

**Comment by justintaddei** [comment]
My pleasure @toniengelhardt 

I can't call it "The material-ripple directive for Vue that actually works" if it doesn't actually work :)

**Comment by toniengelhardt** [comment]
True that. But not judging, I know the pain with browser shenanigans, esp. Safari.
